package com.eventify.eventify.services.email;

public class BodyEmail {
    public static String creadeHtmlBodyToSendCode(String code, String validUntilMinutes) {
        String htmlCodeContent = "<!DOCTYPE html>"
                + "<html lang=\"pt-BR\">"
                + "<head>"
                + "    <meta charset=\"UTF-8\">"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
                + "    <title>Verificação de Email</title>"
                + "    <style>"
                + "        body {"
                + "            font-family: Arial, sans-serif;"
                + "            background-color: #f4f4f4;"
                + "            color: #333333;"
                + "            margin: 0;"
                + "            padding: 0;"
                + "        }"
                + "        .container {"
                + "            max-width: 600px;"
                + "            margin: 0 auto;"
                + "            background-color: #ffffff;"
                + "            padding: 20px;"
                + "            border: 1px solid #dddddd;"
                + "            border-radius: 5px;"
                + "        }"
                + "        .header {"
                + "            text-align: center;"
                + "            background-color: #14AD47;"
                + "            color: #ffffff;"
                + "            padding: 10px 0;"
                + "            border-radius: 5px 5px 0 0;"
                + "        }"
                + "        .content {"
                + "            padding: 20px;"
                + "            text-align: center;"
                + "        }"
                + "        .code {"
                + "            font-size: 24px;"
                + "            font-weight: bold;"
                + "            color: #14AD47;"
                + "            margin: 20px 0;"
                + "        }"
                + "        .footer {"
                + "            text-align: center;"
                + "            color: #777777;"
                + "            font-size: 12px;"
                + "            margin-top: 20px;"
                + "        }"
                + "    </style>"
                + "</head>"
                + "<body>"
                + "    <div class=\"container\">"
                + "        <div class=\"header\">"
                + "            <h1>Eventify</h1>"
                + "        </div>"
                + "        <div class=\"content\">"
                + "            <p>Seu código é:</p>"
                + "            <p class=\"code\">" + code + "</p>"
                + "            <p>Insira este código na plataforma. Código válido pelos próximos " + validUntilMinutes
                + " minutos.</p>"
                + "        </div>"
                + "        <div class=\"footer\">"
                + "            <p>&copy; 2024 Eventify. Todos os direitos reservados.</p>"
                + "        </div>"
                + "    </div>"
                + "</body>"
                + "</html>";
        return htmlCodeContent;
    }
}
