version: "2"
services:
  postgres-eventify:
    image: postgres:15
    container_name: postgres-eventify
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eventify
    ports:
      - "5432:5432"
    networks:
      - my-networks

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - my-networks
    depends_on:
      - postgres-eventify

networks:
  my-networks:
    driver: bridge