version: "2"
services:
  postgres-eventify:
    image: postgres:15
    container_name: postgres-eventify
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=eventify
    volumes:
      - ./infra/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
    networks:
      - my-networks

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge
