INSERT INTO account (username, email, image_data, is_verified) VALUES
('Ana Silva', 'ana.silva@example.com', NULL, TRUE),
('Bruno Santos', 'bruno.santos@example.com', NULL, TRUE),
('Carlos Morais', 'carlos.morais@example.com', NULL, FALSE),
('Daniela Ferreira', 'daniela.ferreira@example.com', NULL, TRUE),
('Eduardo Pereira', 'eduardo.pereira@example.com', NULL, FALSE),
('Fernanda Rocha', 'fernanda.rocha@example.com', NULL, TRUE),
('Gabriel Lima', 'gabriel.lima@example.com', NULL, TRUE),
('Helena Costa', 'helena.costa@example.com', NULL, FALSE),
('Igor Nascimento', 'igor.nascimento@example.com', NULL, TRUE),
('Juliana Martins', 'juliana.martins@example.com', NULL, FALSE),
('Joao Silva', 'joao@example.com', 'https://storage.cloud.google.com/eventify-images/users/12/1.png', TRUE);

INSERT INTO account_password (account_id, user_password, created_at, active, staging, verification_code, code_valid_until) VALUES
(1, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_1', NOW() + INTERVAL '1 day'),
(2, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_2', NOW() + INTERVAL '1 day'),
(3, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_3', NOW() + INTERVAL '1 day'),
(4, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_4', NOW() + INTERVAL '1 day'),
(5, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_5', NOW() + INTERVAL '1 day'),
(6, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_6', NOW() + INTERVAL '1 day'),
(7, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_7', NOW() + INTERVAL '1 day'),
(8, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_8', NOW() + INTERVAL '1 day'),
(9, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_9', NOW() + INTERVAL '1 day'),
(10, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_10', NOW() + INTERVAL '1 day'),
(11, '$2a$12$NT184t2tjpjm1JCQ2zpEXu/wQhKklLXSkmaJiPlw06iae4gGXYCnq', NOW(), TRUE, FALSE, 'verification_code_example', NOW() + INTERVAL '1 hour');

INSERT INTO friend (account_id, friend_id, sended_at, acepted_at) VALUES
(1, 2, NOW(), NOW() + INTERVAL '1 hour'),
(1, 3, NOW(), NULL),
(2, 4, NOW(), NOW() + INTERVAL '1 hour'),
(3, 5, NOW(), NULL),
(4, 6, NOW(), NOW() + INTERVAL '1 hour'),
(5, 7, NOW(), NULL),
(6, 8, NOW(), NOW() + INTERVAL '1 hour'),
(7, 9, NOW(), NULL),
(8, 10, NOW(), NOW() + INTERVAL '1 hour'),
(9, 1, NOW(), NULL),
(11, 1, NOW(), NOW() + INTERVAL '1 hour'),
(11, 2, NOW(), NULL),
(11, 3, NOW(), NOW() + INTERVAL '1 hour'),
(11, 4, NOW(), NOW() + INTERVAL '1 hour'),
(5, 11, NOW(), NULL),
(6, 11, NOW(), NOW() + INTERVAL '1 hour'),
(7, 11, NOW(), NOW() + INTERVAL '1 hour');

INSERT INTO meetup (title, information, created_at, local_name, cep_address, state_address, city_address, neighborhood_address, number_address, street_address, complement_address, latitude, longitude, date_start, date_end, stage, pix_key) VALUES
('Churrasco na Praça', 'Venha se divertir com um delicioso churrasco!', NOW(), 'Parque do Ibirapuera', '12345-678', 'São Paulo', 'São Paulo', 'Vila Mariana', '10', 'Avenida Pedro Álvares Cabral', 'complemento', -23.5875, -46.6579, NOW() + INTERVAL '1 day', NOW() + INTERVAL '2 days', 'created', 'pix_key_1'),
('Virada de Ano', 'Celebre a virada do ano com a gente!', NOW(), 'Praça da Sé', '12345-679', 'São Paulo', 'São Paulo', 'Sé', '20', 'Praça da Sé', 'complemento', -23.5505, -46.6342, NOW() + INTERVAL '2 days', NOW() + INTERVAL '3 days', 'started', 'pix_key_2'),
('Festival de Música', 'Um dia de muita música e diversão!', NOW(), 'Anhangabaú', '12345-680', 'São Paulo', 'São Paulo', 'Centro', '30', 'Avenida São João', 'complemento', -23.5500, -46.6345, NOW() + INTERVAL '3 days', NOW() + INTERVAL '4 days', 'finished', 'pix_key_3'),
('Feira Gastronômica', 'Aproveite sabores do mundo todo!', NOW(), 'Rua dos Três Irmãos', '12345-681', 'São Paulo', 'São Paulo', 'Vila Madalena', '40', 'Rua dos Três Irmãos', 'complemento', -23.5502, -46.6944, NOW() + INTERVAL '4 days', NOW() + INTERVAL '5 days', 'canceled', 'pix_key_4'),
('Cine ao Ar Livre', 'Venha assistir a um filme sob as estrelas!', NOW(), 'Praça Charles Miller', '12345-682', 'São Paulo', 'São Paulo', 'Pacaembu', '50', 'Praça Charles Miller', 'complemento', -23.5490, -46.6515, NOW() + INTERVAL '5 days', NOW() + INTERVAL '6 days', 'created', 'pix_key_5'),
('Show de Rock', 'Uma noite de muito rock e diversão!', NOW(), 'Teatro Municipal', '12345-683', 'São Paulo', 'São Paulo', 'Centro', '60', 'Praça Ramos de Azevedo', 'complemento', -23.5502, -46.6341, NOW() + INTERVAL '6 days', NOW() + INTERVAL '7 days', 'started', 'pix_key_6'),
('Piquenique na Vila', 'Traga seu lanche e venha se divertir!', NOW(), 'Praça do Pôr do Sol', '12345-684', 'São Paulo', 'São Paulo', 'Alto de Pinheiros', '70', 'Rua Diógenes Ribeiro de Lima', 'complemento', -23.5640, -46.6930, NOW() + INTERVAL '7 days', NOW() + INTERVAL '8 days', 'finished', 'pix_key_7'),
('Festa Junina', 'Venha dançar e se divertir com as nossas tradições!', NOW(), 'Escola de Samba', '12345-685', 'São Paulo', 'São Paulo', 'Itaim Bibi', '80', 'Rua do Rocio', 'complemento', -23.5910, -46.6880, NOW() + INTERVAL '8 days', NOW() + INTERVAL '9 days', 'canceled', 'pix_key_8'),
('Caminhada Ecológica', 'Vamos juntos cuidar do meio ambiente!', NOW(), 'Parque da Água Branca', '12345-686', 'São Paulo', 'São Paulo', 'Água Branca', '90', 'Rua Doutor Francisco Dória', 'complemento', -23.5480, -46.6650, NOW() + INTERVAL '9 days', NOW() + INTERVAL '10 days', 'created', 'pix_key_9'),
('Festival de Dança', 'Um dia para celebrar a dança!', NOW(), 'Centro Cultural', '12345-687', 'São Paulo', 'São Paulo', 'Sé', '100', 'Avenida São João', 'complemento', -23.5500, -46.6340, NOW() + INTERVAL '10 days', NOW() + INTERVAL '11 days', 'started', 'pix_key_10');

INSERT INTO meetup_image (meetup_id, image_data, is_profile) VALUES
(1,  'https://storage.cloud.google.com/eventify-images/events/1/1.png',true),
(2,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true),
(3,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true),
(4,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true),
(5,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true),
(6,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true),
(7,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true),
(8,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true),
(9,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true),
(10,  'https://storage.cloud.google.com/eventify-images/events/1/1.png', true);

INSERT INTO participate (account_id, meetup_id, role_participant, active, sended_at, acepted_at) VALUES
(1, 1, 'organizer', TRUE, NOW(), NULL),
(2, 2, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(3, 3, 'organizer', TRUE, NOW(), NULL),
(4, 4, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(5, 5, 'organizer', TRUE, NOW(), NULL),
(6, 6, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(7, 7, 'organizer', TRUE, NOW(), NULL),
(8, 8, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(9, 9, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(10, 10, 'organizer', TRUE, NOW(), NULL),
(11, 1, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(11, 2, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(11, 3, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(11, 4, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(11, 5, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(11, 6, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(11, 7, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(11, 8, 'participant', TRUE, NOW(), NOW() + INTERVAL '5 hours'),
(11, 9, 'organizer', TRUE, NOW(), NULL),
(11, 10, 'participant', TRUE, NOW(), NULL);

INSERT INTO management (participate_id, managment_at, type_action) VALUES
(1, NOW(), 'create'),
(2, NOW(), 'create'),
(3, NOW(), 'create'),
(4, NOW(), 'create'),
(5, NOW(), 'create'),
(6, NOW(), 'create'),
(7, NOW(), 'create'),
(8, NOW(), 'create'),
(9, NOW(), 'create'),
(10, NOW(), 'create');

INSERT INTO expanses (meetup_id, cost, created_at, about) VALUES
(1, 150.75, NOW(), 'Custo de alimentos e bebidas para o churrasco, incluindo carnes, acompanhamentos e refrigerantes.'),
(1, 200.50, NOW(), 'Despesas com locação de mesas, cadeiras e utensílios para o evento.'),
(1, 75.25, NOW(), 'Despesas com decoração e toalhas para as mesas.'),
(2, 250.00, NOW(), 'Custo de fogos de artifício e decoração para a virada de ano.'),
(2, 100.99, NOW(), 'Despesas com segurança para o evento na praça.'),
(2, 70.45, NOW(), 'Custo de banheiros químicos para os participantes.'),
(3, 300.30, NOW(), 'Contratação de bandas e equipamentos de som para o festival de música.'),
(3, 120.60, NOW(), 'Despesas com publicidade e divulgação do evento.'),
(4, 180.80, NOW(), 'Despesas com alimentos de diferentes países para a feira gastronômica.'),
(4, 220.20, NOW(), 'Custo de aluguel de mesas e cadeiras para os expositores.'),
(5, 220.55, NOW(), 'Custo de aluguel de telões e projetores para o cine ao ar livre.'),
(5, 80.75, NOW(), 'Despesas com pipoca e bebidas para os espectadores.'),
(6, 400.40, NOW(), 'Pagamento para as bandas e técnicos de som do show de rock.'),
(6, 150.85, NOW(), 'Custo de segurança para o evento e controle de acesso.'),
(7, 100.10, NOW(), 'Custo de alimentos e bebidas para o piquenique.'),
(7, 50.25, NOW(), 'Despesas com atividades recreativas para crianças.'),
(8, 350.90, NOW(), 'Despesas com decoração e animação da festa junina.'),
(8, 100.50, NOW(), 'Custo de alimentos típicos e bebidas.'),
(9, 200.65, NOW(), 'Custo de materiais para a caminhada ecológica, incluindo lixeiras e água.'),
(9, 50.80, NOW(), 'Despesas com camisetas para os participantes.'),
(10, 300.99, NOW(), 'Contratação de dançarinos e aluguel de espaço para o festival de dança.'),
(10, 150.10, NOW(), 'Custo de materiais para as oficinas de dança durante o evento.');

INSERT INTO payment (account_id, expanse_id, paid_at, value_pay, about, type_payment) VALUES
(1, 1, NOW(), 100.00, 'Payment for expense 1', 'credit_card'),
(2, 2, NOW(), 150.00, 'Payment for expense 2', 'debit_card'),
(3, 3, NOW(), 200.00, 'Payment for expense 3', 'pix'),
(4, 4, NOW(), 250.00, 'Payment for expense 4', 'cash'),
(5, 5, NOW(), 300.00, 'Payment for expense 5', 'credit_card'),
(6, 6, NOW(), 350.00, 'Payment for expense 6', 'debit_card'),
(7, 7, NOW(), 400.00,  'Payment for expense 7', 'pix'),
(8, 8, NOW(), 450.00, 'Payment for expense 8', 'cash'),
(9, 9, NOW(), 500.00, 'Payment for expense 9', 'credit_card'),
(10, 10, NOW(), 550.00, 'Payment for expense 10', 'debit_card');